<!--
  -- A forum software for use in a school in China.
  -- Copyright (C) 2023-2024 Fustigate & YZ9551(YXZ)
  --
  -- This program is free software: you can redistribute it and/or modify
  -- it under the terms of the GNU General Public License as published by
  -- the Free Software Foundation, either version 3 of the License, or
  -- (at your option) any later version.
  --
  -- This program is distributed in the hope that it will be useful,
  -- but WITHOUT ANY WARRANTY; without even the implied warranty of
  -- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  -- GNU General Public License for more details.
  --
  -- You should have received a copy of the GNU General Public License
  -- along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<!-- vim: set ts=2 sts=2 sw=2: -->
<script setup>
  const props = defineProps([])
</script>

<template>
<div class="loadingio-spinner-bean-eater-4ad7mpbk3xs"><div class="ldio-lmjvil5wyo">
<div><div></div><div></div><div></div></div><div><div></div><div></div><div></div></div>
</div></div>
</template>

<style scoped>
@keyframes ldio-lmjvil5wyo-1 {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(-45deg) }
  100% { transform: rotate(0deg) }
}
@keyframes ldio-lmjvil5wyo-2 {
    0% { transform: rotate(180deg) }
   50% { transform: rotate(225deg) }
  100% { transform: rotate(180deg) }
}
.ldio-lmjvil5wyo > div:nth-child(2) {
  transform: translate(-15px,0);
}
.ldio-lmjvil5wyo > div:nth-child(2) div {
  position: absolute;
  top: 20px;
  left: 20px;
  width: 60px;
  height: 30px;
  border-radius: 60px 60px 0 0;
  background: #f8b26a;
  animation: ldio-lmjvil5wyo-1 0.7407407407407407s linear infinite;
  transform-origin: 30px 30px
}
.ldio-lmjvil5wyo > div:nth-child(2) div:nth-child(2) {
  animation: ldio-lmjvil5wyo-2 0.7407407407407407s linear infinite
}
.ldio-lmjvil5wyo > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}@keyframes ldio-lmjvil5wyo-3 {
    0% { transform: translate(95px,0); opacity: 0 }
   20% { opacity: 1 }
  100% { transform: translate(35px,0); opacity: 1 }
}
.ldio-lmjvil5wyo > div:nth-child(1) {
  display: block;
}
.ldio-lmjvil5wyo > div:nth-child(1) div {
  position: absolute;
  top: 46px;
  left: -4px;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #e15b64;
  animation: ldio-lmjvil5wyo-3 0.7407407407407407s linear infinite
}
.ldio-lmjvil5wyo > div:nth-child(1) div:nth-child(1) { animation-delay: -0.9045000000000001s }
.ldio-lmjvil5wyo > div:nth-child(1) div:nth-child(2) { animation-delay: -0.44550000000000006s }
.ldio-lmjvil5wyo > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }
.loadingio-spinner-bean-eater-4ad7mpbk3xs {
  width: 51px;
  height: 51px;
  display: inline-block;
  overflow: hidden;
}
.ldio-lmjvil5wyo {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.51);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-lmjvil5wyo div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
